<?php
$extensionVersion = $this->getExtensionVersion();
?>

<div class="extension-info-box">
    <div class="extension-info-img">
        <img src="http://theextensionlab.com/extension-assets/theextensionlab-config-logo.png" alt="The Extension Lab"/>
    </div>
    <div class="extension-info-header info">
        <h2><?php echo $this->__('Status Colors <span class="version-info">v%s (data v%s)</span>',$extensionVersion,"0.1.0");?></h2>
        <ul>
            <li><h3>Documentation:<span> For full documentation of this extension please visit the <a href="http://docs.theextensionlab.com/status-colors/installation.html" target="_blank">WIKI</a>.</span></h3></li>
            <li><h3>Need support?:<span> <a href="mailto:support@theextensionlab.com"  target="_blank">E-mail Support</a>.</span></h3></li>
            <li><h3>Contribute:<span> <a href="https://github.com/TheExtensionLab/StatusColors" target="_blank">Contribute on github</a></span></h3></li>
        </ul>
    </div>
</div>