<?php
$extensionVersion = $this->getExtensionVersion();
?>

<div class="extension-info-box">
    <div class="extension-info-img">
        <img src="http://theextensionlab.com/extension-assets/theextensionlab-config-logo.png" alt="The Extension Lab"/>
    </div>
    <div class="extension-info-header info">
        <h2><?php echo $this->__('Status Colors <span class="version-info">v%s (data v%s)</span>',$extensionVersion,"0.1.0");?></h2>
        <ul>
            <li><h3>Documentation:<span> For full documentation of this extension please visit the <a href="http://wiki.theextensionlab.com/status-colors">WIKI</a>.</span></h3></li>
            <li><h3>Video user guide:<span> Sometimes following along with a video is easier so if you like you can watch the <a href="wiki.theextensionlab.com/status-colors/video-guide">video guide here</a>.</span></h3></li>
            <li><h3>Need support?:<span> <a href="http://wiki.theextensionlab.com/support">Submit a ticket</a>.</span></h3></li>
            <li><h3>Contribute:<span> <a href="https://github.com/TheExtensionLab/StatusColors">Contribute on github</a> <small>(Note: this is a private repo if you don't have access yet create a support ticket and ask.)</small></span></h3></li>
            <li><h3>Buy us a beer:<span> If you feel that TheExtensionLab have gone way above and beyond the call of duty to help you, and you would like to say thank you with a beer, you can do so <a href="http://www.theextensionlab.com/buy-us-a-beer">here</a>. You won’t be getting anything in return, except for our gratitude! Thanks!</span></h3></li>
        </ul>
    </div>
</div>


<style>
    .extension-info-box{
        border:1px solid #d6d6d6;
        background:#fafafa;
        padding:20px 15px;
        margin-bottom:10px;
        clear:both;
        overflow:hidden;
        box-sizing:border-box;
    }

    .extension-info-box .version-info{
        font-size:0.8em;
        font-weight:normal;
    }

    .extension-info-img{
        width:30%;
        float:left;
    }

    .extension-info-img img{
        max-width:100%;
    }

    .extension-info-box .extension-info-header{
        border-bottom:0px;
        border-left: 1px solid #d6d6d6;
    }

    .extension-info-box .info{
        float:left;
        padding-left:10px;
        min-height:150px;
        width:70%;
        box-sizing:border-box;
    }

    .info h3{
        display:inline;
    }

    .info h3 span{
        color:#000;font-size:14px;font-weight:normal
    }
</style>